language: android
dist: trusty

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-26.0.1                # Build tools version
    - android-26                        # Target SDK version
    - extra-android-m2repository        # Support repo
    - sys-img-armeabi-v7a-android-18    # Emulator

jdk:
  - oraclejdk8

before_script:
  # Create and start an emulator for instrumentation tests.
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew build
  - ./gradlew :autodispose-android:connectedAndroidTest -PdisablePreDex --continue --stacktrace

#after_success:
#  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "SONATYPE_NEXUS_USERNAME TODO"
    - secure: "SONATYPE_NEXUS_PASSWORD TODO"

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
