version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_EMULATOR_TARGET: "24"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "autodispose/build.gradle" }}
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y --no-install-recommends libpulse0
      - run:
          name: Setup emulator
          command: echo y | sdkmanager "platform-tools" "platforms;android-${ANDROID_EMULATOR_TARGET}" "emulator" "system-images;android-${ANDROID_EMULATOR_TARGET};default;armeabi-v7a" && echo "no" | avdmanager create avd --force -n test -k "system-images;android-${ANDROID_EMULATOR_TARGET};default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator -avd test -no-audio -no-boot-anim -no-window -accel on -gpu off
          background: true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
              - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "autodispose/build.gradle" }}
#      - run:
#          name: Install
#          command: ./gradlew build assembleAndroidTest --stacktrace
      - run:
          name: Run Tests
          command: chmod +x android-wait-for-emulator.sh && ./android-wait-for-emulator.sh && ./gradlew check connectedCheck --stacktrace
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results
